// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plqmwauwexlbofyyxojb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscW13YXV3ZXhsYm9meXl4b2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDM3NDksImV4cCI6MjA2MzM3OTc0OX0.nLy_Ty2NwEbIbuvREvT41tWCh1RlIivoXfVMTcFycbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);